
version: '3.5'
  
services:

  pets:
    container_name: pets
    hostname: pets
    image: postgres
    ports:
      - "54321:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - /data/volumes/myproject/pets:/var/lib/postgresql/data/