
version: '3.5'
  
services:

  pets:
    container_name: pets
    hostname: pets
    image: postgres
    ports:
      - "5433:5433"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pets:/var/lib/postgresql/data
volumes:
 pets:
    driver: local
